### ISSUE TITLE
Any plan for git 2.62?

### ISSUE THREAD

**Issue by benyaminl** [iusrepo/git222#7]
Any Plan for git 2.62 for centos? Or it's simply isn't possible?

**Comment by carlwgeorge** [comment]
Assuming you meant git 2.26 (2.62 doesn't exist), I'm not aware of any issues that would prevent creating a git226 package.  IUS creates packages based on user demand, not just because, so if you'd like to see this package please follow our [wishlist instructions](https://github.com/iusrepo/wishlist/blob/master/.github/contributing.md).  These are also linked directly on the [IUS homepage](https://ius.io) as the "Request New Package" button.  The wishlist is also linked to in our [FAQ](https://ius.io/faq#can-ius-add-a-package-for-software).
