### ISSUE TITLE
git difftool missing

### ISSUE THREAD

**Issue by amirgon** [iusrepo/git222#9]
It looks like `git-difftool--helper` is missing from the repo, and prevents `git difftool` from functioning.

```
# rpm -q --whatprovides /usr/libexec/git-core/git-difftool--helper
file /usr/libexec/git-core/git-difftool--helper is not owned by any package
# rpm -q --whatprovides /usr/libexec/git-core/git-diff
git222-core-2.22.4-1.el7.ius.x86_64
```

More details on a [StackOverflow issue](https://stackoverflow.com/questions/63148526/why-does-git-difftool-return-cannot-run-git-difftool-helper-error).

**Comment by carlwgeorge** [comment]
`/usr/libexec/git-core/git-difftool--helper` is not missing from the repository.  It is part of the main git222 package, not git222-core.  git222 was forked from the [Fedora git package](https://src.fedoraproject.org/rpms/git).  It follows the same layout, with a minimal set of functionality in the git222-core package, and the rest of the functionality (and all their dependencies) in the main git222 package.

```
# repoquery --whatprovides /usr/libexec/git-core/git-difftool--helper | sort -V
git222-0:2.22.2-1.el7.ius.x86_64
git222-0:2.22.3-1.el7.ius.x86_64
git222-0:2.22.4-1.el7.ius.x86_64
git224-0:2.24.2-1.el7.ius.x86_64
git224-0:2.24.3-1.el7.ius.x86_64
git-0:1.8.3.1-21.el7_7.x86_64
git-0:1.8.3.1-22.el7_8.x86_64
git-0:1.8.3.1-23.el7_8.x86_64
```

Your rpm query didn't show you this because that only operates on installed packages, not what is in the repository.  repoquery is the tool you need for that.
